#!/bin/bash
# Author - BadiGard
# $1 (parameter 1) is the file's name

if [ -z "$1" ]; then
	echo USAGE: ${0} \<file name\>
	exit
fi
file_type=$( cut -d "." -f2 <<< "$1" )

if [ "$file_type" == "h" ]; then
	file_type="c"
fi 

if [ -e /usr/share/nano/${file_type}.nanorc]
    cp /usr/share/nano/${file_type}.nanorc ~/.nanorc
else
    rm ~/.nanorc
fi

nano "$1"
